FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETARCH

WORKDIR /app
COPY console-${TARGETARCH} /app/console

# The nonroot user is built into the distroless image
USER nonroot

EXPOSE 9090
ENTRYPOINT ["/app/console", "server"] 